# Establish with python dependencies need to be tested
name: Python Unit Test Workflow

on:
  workflow_call:
    inputs:
      root_directory:
        required: true
        type: string
    outputs:
      changed_projects:
          description: "List of changed python projects paths"
          value: ${{ jobs.check_changes.outputs.changed_projects }}

jobs:
  check_changes:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    outputs:
      changed_projects: ${{ steps.output.outputs.changed_projects }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
          cache-dependency-path: |
            tools/ci/poetry.lock

      - name: Install poetry dependencies
        working-directory: tools/ci
        run: |
          # We need to tell poetry to use correct python version
          poetry env use "3.10"
          poetry install --no-interaction --no-dev
          poetry run pip list

      - name: Run unit tests
        id: output
        working-directory: tools/ci
        run: |
          echo changed_projects=$(poetry run python -m testbot \
            -O \
            --root-dir ${{inputs.root_directory}} \
            >> $GITHUB_OUTPUT
