# Establish with python dependencies need to be tested
name: Python Unit Test Workflow

on:
  workflow_call:
    inputs:
      root_directory:
        required: true
        type: string
    outputs:
      changed_projects:
          description: "List of changed python projects paths"
          value: ${{ jobs.check_changes.outputs.changed_projects }}

jobs:
  check_changes:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    outputs:
      changed_projects: ${{ steps.output.outputs.changed_projects }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: fsherratt/github-actions-playground/workflows/install-poetry
        with:
          python_version: '3.10'
          poetry_version: '==1.4.2'
          working_directory: './tools/ci'

      - name: Find Changed Subprojects
        id: output
        working-directory: tools/ci
        run: |
          echo changed_projects=$(poetry run python -m testbot \
            -O \
            --root-dir ${{inputs.root_directory}}) \
            >> $GITHUB_OUTPUT
