# This workflow will install Python dependencies and run unittests with a single version of Python
# The workflow also run code-quality analysis across code
# The `work_directory` input is used to specify the module working directory

name: Python Code Quality Workflow

on:
  workflow_call:
    inputs:
      work_directory:
        required: true
        type: string

jobs:
  code-quality:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: fsherratt/github-actions-playground/workflows/install-poetry
        with:
          python_version: '3.10'
          working_directory: ${{ inputs.work_directory }}
  
      - uses: fsherratt/github-actions-playground/workflows/python-lint
        with:
          work_directory: ${{ inputs.work_directory }}
