# This workflow will install Python dependencies and run unittests with a single version of Python
# The workflow also run code-quality analysis across code
# The `work_directory` input is used to specify the module working directory

name: Python Unit Test Workflow

on:
  workflow_call:
    inputs:
      work_directory:
        required: true
        type: string

jobs:
  unit-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: github-actions-playground/workflows/install-poetry@composable-actions
        with:
          python-version: '3.10'
          working-directory: ${{ inputs.work_directory }}

      - name: Install poetry dependencies
        working-directory: ${{ inputs.work_directory }}
        run: |
          poetry add coverage
          poetry run pip list

      - name: Setup Unittest Runner
        run: |
          cp tools/ci/unittest_runner/unittest_runner.py \
          ${{ inputs.work_directory }}/unittest_runner.py
          

      - name: Run unit tests
        working-directory: ${{ inputs.work_directory }}
        run: poetry run python unittest_runner.py --name ${{ inputs.work_directory }}
      
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-result
          path: ${{ inputs.work_directory }}/py_ut_*.json
          retention-days: 1

      - name: Archive Coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-coverage
          path: ${{ inputs.work_directory }}/py_cov_*.md
          retention-days: 5
