# This workflow will install Python dependencies and run unittests with a single version of Python
# The workflow also run code-quality analysis across code
# The `work_directory` input is used to specify the module working directory

name: Python Unit Test Workflow

on:
  workflow_call:
    inputs:
      work_directory:
        required: true
        type: string

jobs:
  unit-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
          cache-dependency-path: |
            ${{ inputs.work_directory }}/poetry.lock

      - name: Install poetry dependencies
        working-directory: ${{ inputs.work_directory }}
        run: |
          # We need to tell poetry to use correct python version
          poetry env use "3.10"
          poetry install --no-interaction --only main
          poetry run pip list

      - name: Copy Runner
        run: |
          cp tools/ci/unittest_runner/unittest_runner.py ${{ inputs.work_directory }}/unittest_runner.py 

      - name: Run unit tests
        working-directory: ${{ inputs.work_directory }}
        run: |
          poetry run python unittest_runner.py

      - name: Generate_Artifact_Name
        id: artifact_name
        run: |
          echo art_name=$(echo unit-test-result-${{ inputs.work_directory }} | tr / _ ) \
          >> $GITHUB_OUTPUT

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          # name: unit-test-result
          name: ${{ steps.artifact_name.outputs.art_name}}
          path: ${{ inputs.work_directory }}/result_data.json
          retention-days: 1