# This workflow will establish which workflows should be run and trigger them appropriately
name: Test Runner

on:
  # Run during pull request containing python files
  push:
    branch: 
      "test-python-symlink"
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        shell: bash
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install poetry dependencies
        working-directory: test/project_2
        shell: bash
        run: |
          poetry env use 3.10
          poetry install --no-interaction

      - name: Symlink setup
        working-directory: test/project_2
        shell: bash
        run: |
          poetry shell
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Test symlink
        run: |
          python -m pip list
